### ISSUE TITLE
MiPlugBaseEnhanced always returns timeout.

### ISSUE THREAD

**Issue by eZioPan** [YinHangCode/homebridge-mi-outlet#14]
Hardware: MiPlugBaseEnhanced
Hardware type: ZNCZ03CM
Hardware firmare version: 1.3.0_93
homebridge version: 0.4.45
homebridge-mi-outlet version: 0.3.0

Here is the log:
```
Sep 17 00:21:41 ePRP3 homebridge[12096]: [2018-9-17 00:21:41] [MiOutletPlatform] [MiOutletPlatform][ERROR]MiPlugBaseEnhanced - Outlet - getPower Error: Error: Call to device timed out
Sep 17 00:21:41 ePRP3 homebridge[12096]: Sun, 16 Sep 2018 16:21:41 GMT Accessory [Homebridge] Got Characteristic "On" value: undefined
Sep 17 00:21:41 ePRP3 homebridge[12096]: Sun, 16 Sep 2018 16:21:41 GMT Accessory [Homebridge] Error getting value for Characteristic "On": Call to device timed out
Sep 17 00:21:41 ePRP3 homebridge[12096]: [2018-9-17 00:21:41] [MiOutletPlatform] [MiOutletPlatform][ERROR]MiPlugBase - MiPlugBaseEnhanced - getTemperature Error: Error: Call to device timed out
Sep 17 00:21:41 ePRP3 homebridge[12096]: Sun, 16 Sep 2018 16:21:41 GMT Accessory [Homebridge] Got Characteristic "Current Temperature" value: undefined
Sep 17 00:21:41 ePRP3 homebridge[12096]: Sun, 16 Sep 2018 16:21:41 GMT Accessory [Homebridge] Error getting value for Characteristic "Current Temperature": Call to device timed out
Sep 17 00:21:41 ePRP3 homebridge[12096]: [2018-9-17 00:21:41] [MiOutletPlatform] [MiOutletPlatform][ERROR]MiPlugBaseEnhanced - SwitchUSB - getUSBPower Error: Error: Call to device timed out
Sep 17 00:21:41 ePRP3 homebridge[12096]: Sun, 16 Sep 2018 16:21:41 GMT Accessory [Homebridge] Got Characteristic "On" value: undefined
Sep 17 00:21:41 ePRP3 homebridge[12096]: Sun, 16 Sep 2018 16:21:41 GMT Accessory [Homebridge] Error getting value for Characteristic "On": Call to device timed out  
```
Btw, I have an old MiPlugBaseWithUSB which runs perfect.

**Comment by YinHangCode** [comment]
make sure ip or token is right.

**Comment by eZioPan** [comment]
Yes, I think I get right token and ip.
I use ```PacketSender``` sending ```Miio Hello Packet``` to the device and capture the return token. Then I try ```miio``` which returns the same token as PacketSender. But *I don't have an Android device*, so I can't verify it.
I have tried to use both ```standard and static-mapped DHCP address```, both returned timeout.
In the ```debug mode``` I see something like this. (Sorry I have no plug device right now, I can only remember this.)
```
miio.packet -> <miio-protocol-like binary code>
miio.packet <- <miio-protocol-like binary code>
[the ip of mi plug] <- [null]
```
I have homebridge runs on two devices, one on ```Synology``` with the homebridge plugin (with ```MiPlugBaseWithUSB``` runs well), another on ```raspberry pi``` (with some other plugins like ```homebridge-mi-aqara``` and ```homebridge-aqara``` runs well), both devices report timeout on ```MiPlugBaseEnhanced```.
Another thing is that ```raspberrypi``` uses ```eth0``` as internet interface, I don't know if this matter.

**Comment by YinHangCode** [comment]
It's recommended to be get token through miio2.db

**Comment by Skull09rus** [comment]
Hi! same problem, raspberry + PacketSender 
My cfg
 {          "platform": "MiOutletPlatform",
            "deviceCfgs": [
                {
                    "type": "MiPlugBaseEnhanced",
                    "ip": "192.168.1.***",
                    "token": "32 chars from PacketSender",
                    "outletName": "living room outlet2",
                    "outletDisable": false,
                    "temperatureName": "living room outlet2 temperature",
                    "temperatureDisable": false,
                    "switchUSBName": "living room outlet2 usb switch",
                    "switchUSBDisable": false,
                    "switchLEDName": "living room outlet2 led light switch",
                    "switchLEDDisable": true
                }
            ]
        }


[2018-9-28 01:03:56] [MiOutletPlatform] [MiOutletPlatform][ERROR]MiPlugBaseEnhanced - Outlet - getPower Error: Error: Call to device timed out
[2018-9-28 01:05:07] [MiOutletPlatform] [MiOutletPlatform][ERROR]MiPlugBase - MiPlugBaseEnhanced - getTemperature Error: Error: Call to device timed out
[2018-9-28 01:05:07] [MiOutletPlatform] [MiOutletPlatform][ERROR]MiPlugBaseEnhanced - Outlet - getPower Error: Error: Call to device timed out
[2018-9-28 01:05:07] [MiOutletPlatform] [MiOutletPlatform][ERROR]MiPlugBaseEnhanced - SwitchUSB - getUSBPower Error: Error: Call to device timed out
[2018-9-28 01:06:27] [MiOutletPlatform] [MiOutletPlatform][ERROR]MiPlugBaseEnhanced - Outlet - getPower Error: Error: Call to device timed out

**Comment by eZioPan** [comment]
Finally, I get some new information.
From my test, new version `MiHome iOS app` seems to **change token** after connection, so the only way to get right token is fetching from `miio2.db` of `Android device` or `[userid]_mihome.sqlite` of `iOS device`.
@Skull09rus you can check this page: [obtain_token](https://github.com/jghaanstra/com.xiaomi-miio/blob/master/docs/obtain_token.md#method-3---obtain-mi-home-device-token-for-devices-that-hide-their-tokens-after-setup) for more information.
This may due to safety concerns, I don't think this could be changed in future.
