### ISSUE TITLE
大神，求助！！

### ISSUE THREAD

**Issue by philboycn** [YinHangCode/homebridge-mi-outlet#2]
家里小米挺多一直用大神的homebridge插件，看到大神新出插线板插件和网关FM插件，就想试试。安装设置了插线板插件，咦，没有东西出来，算了再安装FM插件试试，安装好改好config重启homebridge，所有插件全部不翼而飞，ios家庭app里显示只剩下孤零零的一个网关了！！这。。怎么回事啊？

**Comment by YinHangCode** [comment]
配置文件 发上来看看

**Comment by philboycn** [comment]
homebridge也是正常启动，各log都显示正常，米家app软件正常，home app网关无法连接，删除后再添加配件就找不到网关了。。

[config.zip](https://github.com/YinHangCode/homebridge-mi-outlet/files/1274177/config.zip)

**Comment by YinHangCode** [comment]
看了下配置文件 看起来没问题 你有清粗缓存文件么？hb启动的时候有报错信息么？
btw, 你这么多插件 都挂在一个hb下，hb会很慢 建议分开hb。

**Comment by philboycn** [comment]
好像是网关最大支持99个设备，到100个设备就无法显示了，不知道是这个原因不。

**Comment by YinHangCode** [comment]
这个我还没试过 没这么多设备
你可以通过hb的-U和-P参数启动多个hb 这样合理一些、所有设备都挂在一个hb下一个是慢、再一个问题 其中一个插件有问题会导致整个hb都挂掉

**Comment by philboycn** [comment]
删除到99个以下就又出现了，插线板插件和FM插件都正常！非常感谢大神的辛勤工作，家里已实现siri智能家庭！
